// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEHV8hGyBAyWhZ-zhiyBetX_ASgTLkyNA',
    appId: '1:911420816254:web:1f71954ba15f582428112f',
    messagingSenderId: '911420816254',
    projectId: 'medicalreminder-a1008',
    authDomain: 'medicalreminder-a1008.firebaseapp.com',
    storageBucket: 'medicalreminder-a1008.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQbp_gKgqJsHRABuM9XCMaAJvJyZOXc0I',
    appId: '1:911420816254:android:3d6d3268c27c244b28112f',
    messagingSenderId: '911420816254',
    projectId: 'medicalreminder-a1008',
    storageBucket: 'medicalreminder-a1008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ44Zh9EXMSeVdM5kK3zn9rjry8B13T0E',
    appId: '1:911420816254:ios:768c9f4356203f6128112f',
    messagingSenderId: '911420816254',
    projectId: 'medicalreminder-a1008',
    storageBucket: 'medicalreminder-a1008.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ44Zh9EXMSeVdM5kK3zn9rjry8B13T0E',
    appId: '1:911420816254:ios:768c9f4356203f6128112f',
    messagingSenderId: '911420816254',
    projectId: 'medicalreminder-a1008',
    storageBucket: 'medicalreminder-a1008.appspot.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEHV8hGyBAyWhZ-zhiyBetX_ASgTLkyNA',
    appId: '1:911420816254:web:62826569fc474bea28112f',
    messagingSenderId: '911420816254',
    projectId: 'medicalreminder-a1008',
    authDomain: 'medicalreminder-a1008.firebaseapp.com',
    storageBucket: 'medicalreminder-a1008.appspot.com',
  );
}
